apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-neuvector
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.1.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the NeuVector Core Helm chart for container security platform.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-neuvector

    Installs the NeuVector Core Helm chart using Crossplane and the Helm provider.
    NeuVector is a full lifecycle container security platform.
  repository: ghcr.io/hops-ops/helm-neuvector
  source: github.com/hops-ops/helm-neuvector
